In [1]:
import pandas as pd
import numpy as np

train = pd.read_csv("../data/raw/train.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [2]:
print("Rows:", train.shape[0])
print("Columns:", train.shape[1])

Rows: 421570
Columns: 5

In [3]:
train.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [4]:
train.columns.tolist()

['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday']

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB

In [6]:
train.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [7]:
print("Duplicate rows:", train.duplicated().sum())

Duplicate rows: 0

In [8]:
train.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

In [9]:
features = pd.read_csv("../data/raw/features.csv")
stores = pd.read_csv("../data/raw/stores.csv")

In [10]:
print("FEATURES")
print(features.shape)
display(features.head())

print("\nSTORES")
print(stores.shape)
display(stores.head())

FEATURES
(8190, 12)

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

STORES
(45, 3)

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [11]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB

In [12]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [13]:
sales = train.copy()

In [14]:
sales['Date'] = pd.to_datetime(sales['Date'])
features['Date'] = pd.to_datetime(features['Date'])

In [15]:
print(sales['Date'].dtype)
print(features['Date'].dtype)

datetime64[ns]
datetime64[ns]

In [16]:
features.columns.tolist()

['Store',
 'Date',
 'Temperature',
 'Fuel_Price',
 'MarkDown1',
 'MarkDown2',
 'MarkDown3',
 'MarkDown4',
 'MarkDown5',
 'CPI',
 'Unemployment',
 'IsHoliday']

In [17]:
features_for_merge = features.drop(columns=['IsHoliday'])

In [18]:
sales = sales.merge(
    features_for_merge,
    on=['Store', 'Date'],
    how='left'
)

In [19]:
print("Rows:", sales.shape[0])
print("Columns:", sales.shape[1])

Rows: 421570
Columns: 14

In [20]:
sales.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106

In [21]:
sales = sales.merge(
    stores,
    on='Store',
    how='left'
)

In [22]:
print("Rows:", sales.shape[0])
print("Columns:", sales.shape[1])

Rows: 421570
Columns: 16

In [23]:
missing = sales.isnull().sum()

print(missing[missing > 0])

MarkDown1    270889
MarkDown2    310322
MarkDown3    284479
MarkDown4    286603
MarkDown5    270138
dtype: int64

In [24]:
markdown_cols = [
    'MarkDown1',
    'MarkDown2',
    'MarkDown3',
    'MarkDown4',
    'MarkDown5'
]

sales[markdown_cols] = sales[markdown_cols].fillna(0)

In [25]:
sales[markdown_cols].isnull().sum()

MarkDown1    0
MarkDown2    0
MarkDown3    0
MarkDown4    0
MarkDown5    0
dtype: int64

In [26]:
sales = sales.sort_values(['Store', 'Date'])

sales[['CPI', 'Unemployment']] = (
    sales.groupby('Store')[['CPI', 'Unemployment']]
         .transform(lambda x: x.ffill().bfill())
)

In [27]:
sales[['CPI', 'Unemployment']].isnull().sum()

CPI             0
Unemployment    0
dtype: int64

In [28]:
print(sales.isnull().sum())

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Type            0
Size            0
dtype: int64

In [29]:
print("Duplicate rows:", sales.duplicated().sum())

Duplicate rows: 0

In [30]:
sales['Year'] = sales['Date'].dt.year
sales['Month'] = sales['Date'].dt.month
sales['Month_Name'] = sales['Date'].dt.month_name()
sales['Quarter'] = sales['Date'].dt.quarter
sales['Week'] = sales['Date'].dt.isocalendar().week.astype(int)

In [31]:
sales[['Date', 'Year', 'Month', 'Month_Name', 'Quarter', 'Week']].head()

          Date  Year  Month Month_Name  Quarter  Week
0   2010-02-05  2010      2   February        1     5
143 2010-02-05  2010      2   February        1     5
286 2010-02-05  2010      2   February        1     5
429 2010-02-05  2010      2   February        1     5
572 2010-02-05  2010      2   February        1     5

In [32]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 421570 entries, 0 to 421569
Data columns (total 21 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[ns]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
 5   Temperature   421570 non-null  float64
 6   Fuel_Price    421570 non-null  float64
 7   MarkDown1     421570 non-null  float64
 8   MarkDown2     421570 non-null  float64
 9   MarkDown3     421570 non-null  float64
 10  MarkDown4     421570 non-null  float64
 11  MarkDown5     421570 non-null  float64
 12  CPI           421570 non-null  float64
 13  Unemployment  421570 non-null  float64
 14  Type          421570 non-null  object
 15  Size          421570 non-null  int64
 16  Year          421570 non-null  int32
 17  Month         421570 non-null  int32
 18  Month_Name    421570 non-null  object
 19  Quarter       421570 non-null  int32
 20  Week          421570 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(10), int32(3), int64(4), object(2)
memory usage: 63.1+ MB

In [33]:
sales.describe()

,Store,Dept,Date,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Size,Year,Month,Quarter,Week
count,421570.000000,421570.000000,421570,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000,421570.000000
mean,22.200546,44.260317,2011-06-18 08:30:31.963375360,15981.258123,60.090059,3.361027,2590.074819,879.974298,468.087665,1083.132268,1662.772385,171.201947,7.960289,136727.915739,2010.968591,6.449510,2.482767,25.826762
min,1.000000,1.000000,2010-02-05 00:00:00,-4988.940000,-2.060000,2.472000,0.000000,-265.760000,-29.100000,0.000000,0.000000,126.064000,3.879000,34875.000000,2010.000000,1.000000,1.000000,1.000000
25%,11.000000,18.000000,2010-10-08 00:00:00,2079.650000,46.680000,2.933000,0.000000,0.000000,0.000000,0.000000,0.000000,132.022667,6.891000,93638.000000,2010.000000,4.000000,2.000000,14.000000
50%,22.000000,37.000000,2011-06-17 00:00:00,7612.030000,62.090000,3.452000,0.000000,0.000000,0.000000,0.000000,0.000000,182.318780,7.866000,140167.000000,2011.000000,6.000000,2.000000,26.000000
75%,33.000000,74.000000,2012-02-24 00:00:00,20205.852500,74.280000,3.738000,2809.050000,2.200000,4.540000,425.290000,2168.040000,212.416993,8.572000,202505.000000,2012.000000,9.000000,3.000000,38.000000
max,45.000000,99.000000,2012-10-26 00:00:00,693099.360000,100.140000,4.468000,88646.760000,104519.540000,141630.610000,67474.850000,108519.280000,227.232807,14.313000,219622.000000,2012.000000,12.000000,4.000000,52.000000
std,12.785297,30.492054,NaN,22711.183519,18.447931,0.458515,6052.385934,5084.538801,5528.873453,3894.529945,4207.629321,39.159276,1.863296,60980.583328,0.796876,3.243217,1.071341,14.151887

In [34]:
print("Final rows:", sales.shape[0])
print("Final columns:", sales.shape[1])

Final rows: 421570
Final columns: 21

In [35]:
sales[sales['Weekly_Sales'] < 0][
    ['Store', 'Dept', 'Date', 'Weekly_Sales']
].head(20)

       Store  Dept       Date  Weekly_Sales
6048       1    47 2010-02-19       -863.00
6049       1    47 2010-03-12       -698.00
6051       1    47 2010-10-08        -58.00
6562       1    54 2011-01-21        -50.00
6056       1    47 2011-04-08       -298.00
6578       1    54 2011-05-20        -15.00
6057       1    47 2011-07-08       -198.00
6061       1    47 2011-10-14       -498.00
6062       1    47 2011-12-23       -498.00
6063       1    47 2012-02-17       -198.00
6616       1    54 2012-03-09        -21.00
6064       1    47 2012-03-16       -199.00
6163       1    48 2012-03-23       -223.00
2384       1    18 2012-05-04         -1.27
846        1     6 2012-08-10       -139.65
16317      2    48 2010-03-12         -3.00
16090      2    45 2010-04-09       -118.00
16091      2    45 2010-05-07         -0.98
16291      2    47 2010-07-30      -1098.00
16294      2    47 2010-08-20       -498.00

In [36]:
sales.to_csv(
    "../data/processed/sales_cleaned.csv",
    index=False
)

In [37]:
import os

print(os.path.exists("../data/processed/sales_cleaned.csv"))

True

In [38]:
print("Final rows:", sales.shape[0])
print("Final columns:", sales.shape[1])

Final rows: 421570
Final columns: 21

In [39]:
sales.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Type            0
Size            0
Year            0
Month           0
Month_Name      0
Quarter         0
Week            0
dtype: int64

In [40]:
sales.duplicated().sum()

np.int64(0)

In [41]:
sales[sales['Weekly_Sales'] < 0][
    ['Store', 'Dept', 'Date', 'Weekly_Sales']
].head(20)

       Store  Dept       Date  Weekly_Sales
6048       1    47 2010-02-19       -863.00
6049       1    47 2010-03-12       -698.00
6051       1    47 2010-10-08        -58.00
6562       1    54 2011-01-21        -50.00
6056       1    47 2011-04-08       -298.00
6578       1    54 2011-05-20        -15.00
6057       1    47 2011-07-08       -198.00
6061       1    47 2011-10-14       -498.00
6062       1    47 2011-12-23       -498.00
6063       1    47 2012-02-17       -198.00
6616       1    54 2012-03-09        -21.00
6064       1    47 2012-03-16       -199.00
6163       1    48 2012-03-23       -223.00
2384       1    18 2012-05-04         -1.27
846        1     6 2012-08-10       -139.65
16317      2    48 2010-03-12         -3.00
16090      2    45 2010-04-09       -118.00
16091      2    45 2010-05-07         -0.98
16291      2    47 2010-07-30      -1098.00
16294      2    47 2010-08-20       -498.00